### ISSUE TITLE
stem says "dictionary keys changed during iteration" with python 3.8

### ISSUE THREAD

**Issue by atagar** [torproject/nyx#10]
**Migrated from ticket [32552](https://trac.torproject.org/projects/tor/ticket/32552).**

Every single time I try to connect to for from Nyx I get 

```
Traceback (most recent call last):
  File "/bin/nyx", line 11, in <module>
    load_entry_point('nyx==2.1.0', 'console_scripts', 'nyx')()
  File "/usr/lib/python3.8/site-packages/nyx/__init__.py", line 176, in main
    nyx.starter.main()
  File "/usr/lib/python3.8/site-packages/stem/util/conf.py", line 289, in wrapped
    return func(*args, config = config, **kwargs)
  File "/usr/lib/python3.8/site-packages/nyx/starter.py", line 90, in main
    controller = init_controller(
  File "/usr/lib/python3.8/site-packages/nyx/__init__.py", line 325, in init_controller
    TOR_CONTROLLER = stem.connection.connect(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/stem/connection.py", line 291, in connect
    return _connect_auth(control_connection, password, password_prompt, chroot_path, controller)
  File "/usr/lib/python3.8/site-packages/stem/connection.py", line 404, in _connect_auth
    return _connect_auth(control_socket, password, password_prompt, chroot_path, controller)
  File "/usr/lib/python3.8/site-packages/stem/connection.py", line 375, in _connect_auth
    return controller(control_socket, is_authenticated = True)
  File "/usr/lib/python3.8/site-packages/stem/control.py", line 1057, in __init__
    super(Controller, self).__init__(control_socket, is_authenticated)
  File "/usr/lib/python3.8/site-packages/stem/control.py", line 585, in __init__
    self._post_authentication()
  File "/usr/lib/python3.8/site-packages/stem/control.py", line 3902, in _post_authentication
    owning_pid = self.get_conf('__OwningControllerProcess', None)
  File "/usr/lib/python3.8/site-packages/stem/control.py", line 2170, in get_conf
    entries = self.get_conf_map(param, default, multiple)
  File "/usr/lib/python3.8/site-packages/stem/control.py", line 2273, in get_conf_map
    for key in reply:
RuntimeError: dictionary keys changed during iteration
```

Using Arch Linux on a headless server, python 3.8.0b4. Tried both cookie and password authentication methods. Controlport is 9051, inaccessible from outside (firewall set up to allow any internal connections to any port)

**Comment by snooppr** [comment]
"nyx" worked, but at some point it broke with exactly the same error. The search led here, but did not find a solution.

**Solution to the problem** (from the user and from the root user, i.e. update stem 1.7.1 to 1.8.2 twice):
`python3 -m pip install stem -U`
