### ISSUE TITLE
Backtrace: socket.py:243:_send:stem.SocketClosed

### ISSUE THREAD

**Issue by jorti** [torproject/nyx#35]
This backtrace was reported in Fedora 33 with these package versions:

nyx-2.1.0-6.fc33
python-stem-1.8.0-8.fc33
python3-3.9.0-1.fc33.x86_64

```
socket.py:243:_send:stem.SocketClosed

Traceback (most recent call last):
  File "/usr/bin/nyx", line 33, in <module>
    sys.exit(load_entry_point('nyx==2.1.0', 'console_scripts', 'nyx')())
  File "/usr/lib/python3.9/site-packages/nyx/__init__.py", line 176, in main
    nyx.starter.main()
  File "/usr/lib/python3.9/site-packages/stem/util/conf.py", line 289, in wrapped
    return func(*args, config = config, **kwargs)
  File "/usr/lib/python3.9/site-packages/nyx/starter.py", line 128, in main
    nyx.curses.start(nyx.draw_loop, acs_support = config.get('acs_support', True), transparent_background = True, cursor = False)
  File "/usr/lib/python3.9/site-packages/nyx/curses.py", line 219, in start
    curses.wrapper(_wrapper)
  File "/usr/lib64/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/nyx/curses.py", line 217, in _wrapper
    function()
  File "/usr/lib/python3.9/site-packages/nyx/__init__.py", line 221, in draw_loop
    nyx.menu.show_menu()
  File "/usr/lib/python3.9/site-packages/nyx/menu.py", line 212, in show_menu
    cursor.handle_key(nyx.curses.key_input())
  File "/usr/lib/python3.9/site-packages/nyx/menu.py", line 171, in handle_key
    self.selection.select()
  File "/usr/lib/python3.9/site-packages/nyx/menu.py", line 70, in select
    self._callback()
  File "/usr/lib/python3.9/site-packages/stem/control.py", line 3823, in signal
    response = self.msg('SIGNAL %s' % signal)
  File "/usr/lib/python3.9/site-packages/stem/control.py", line 662, in msg
    self._socket.send(message)
  File "/usr/lib/python3.9/site-packages/stem/socket.py", line 460, in send
    self._send(message, lambda s, sf, msg: send_message(sf, msg))
  File "/usr/lib/python3.9/site-packages/stem/socket.py", line 243, in _send
    raise stem.SocketClosed()
stem.SocketClosed

Local variables in innermost frame:
self: <stem.socket.ControlPort object at 0x7ff44fcc0eb0>
message: 'SIGNAL RELOAD'
handler: <function ControlSocket.send.<locals>.<lambda> at 0x7ff44fc8cb80>
```

**Comment by atagar** [comment]
Hi Juan. Nyx should display a message that says the connection has closed rather than crash. Thanks for reporting this.
