### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by JimAppreciator512** [torproject/nyx#56]
I got a tor node up and running of my pi right, I installed nyx, launched it on my control port and was met with this stack trace

```
Exception in thread Thread-5:
Traceback (most recent call last):
        File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
                self.run()
        File "/usr/lib/python3.9/threading.py", line 892, in run
                self._target(*self,_args,**self.kwargs)
        File "/home/---/.local/lib/python3.9/site-packages/nyx/__init__.py", line 745, in halt_panels
                panel.join()
        File "/usr/lib/python3.9/threading.py", line 1028, in join
                raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
Traceback (most recent call last):
        File "/usr/bin/nyx", line 33, in <module>
                sys.exit(load_entry_point('nyx==2.1.0', 'console_scripts', 'nyx')())
        File "/home/---/.local/lib/python3.9/site-packages/nyx/__init__.py", line 176, in main
                nyx.starter.main()
        File "/usr/lib/python3/dist-packages/stem/util/conf.py", line 289, in wrapped
                return func(*args, config = config, **kwargs)
        File "/home/---/.local/lib/python3.9/site-packages/nyx/starter.py", line 128, in main
                nyx.curses/start(nyx.draw_loop, acs_support = config.get('acs_support', True), transparent_background = True, cursor = False)
        File "/home/---/.local/lib/python3.9/site-packages/nyx/curses.py", line 219, in start
                curses.wrapper(_wrapper)
        File "/usr/lib/python3/curses/__init__.py", line 94, in wrapper
                return func(stdscr, *args, **kwds)
        File "/home/---/.local/lib/python3.9/site-packages/nyx/curses.py", line 217, in _wrapper
                function()
        File "/home/---/.local/lib/python3.9/site-packages/nyx/__init__.py", line 194, draw_loop
                interface = nyx_interface()
        File "/home/---/.local/lib/python3.9/site-packages/nyx/__init__.py", line 256, in nyx_interface
                interface()  # constructor sets NYX_INTERFACE
        File "/home/---/.local/lib/python3.9/site-packages/nyx/__init__.py", line 601, in __init__
                first_page_panels.append(nyx.panel.log.LogPanel())
        File "/home/---/.local/lib/python3.9/site-packages/nyx/panel/log.py", line 110, in __init__
                log_location = nyx.log.log_file_path(tor_controller())
        File "/home/---/.local/lib/python3.9/site-packages/nyx/log.py", line 88, in log_file_path
                if entry_comp[1] == 'file':
IndexError: list index out of range
```

I was about to blow my brains out then I made this change to the `log.py` file

```diff
- if entry_comp[1] == 'file':
+ if entry_comp[0] == 'file':
```

then it worked perfectly fine with no issues, curses were a little screwed up for whatever reason but I'm not complaining.

I'm running nyx 2.1.0 from the debian repositories (installed tor-arm & nyx). Reply with any other requested information. Also if the stack trace looks a little funny I copied it by hand :+1:

**Comment by h3xagonal** [comment]
Possibly related to #60

Do not know if you are still here but could you post an excerpt of your torrc that shows the entry for logfile path?

Thank you

**Comment by atagar** [comment]
Great catch! This is definitely a duplicate. Thanks h3xagonal.
