### ISSUE TITLE
pip install nyx [RegataOS - Opensuse]

### ISSUE THREAD

**Issue by Jeiel0rbit** [torproject/nyx#67]
```js
nyx
```
Then it breaks

```js
Traceback (most recent call last):
  File "/usr/bin/nyx", line 11, in <module>
    load_entry_point('nyx==2.1.0.dev0', 'console_scripts', 'nyx')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/nyx-2.1.0.dev0-py3.6.egg/nyx/__init__.py", line 772, in <module>
    import nyx.curses
  File "/usr/lib/python3.6/site-packages/nyx-2.1.0.dev0-py3.6.egg/nyx/curses.py", line 88, in <module>
    import curses
  File "/usr/lib64/python3.6/_import_failed/curses.py", line 19, in <module>
    to install it.""")
ImportError: Module 'curses' is not installed.
```

**Comment by Jeiel0rbit** [comment]
I got help from Google's artificial intelligence (Bard), so it worked:

```js
sudo zypper install python3-curses
```

**Comment by Jeiel0rbit** [comment]
I am sorry.
